name: Run tests on Pull Request

on: [pull_request]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.103'
      - name: Run all tests
        run: |
          dotnet test RealTime.Tests
  npm-package-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Install dependencies
        run: "cd Npm && yarn install"
      - name: Run all tests
        run: jest
